version: '3.0'
services:
  main:
    image: alpha-core:latest
    build: .
    environment:
      - MYSQL_HOST=sql
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=pwd
      - CONSOLE_MODE=False
    ports:
      - "8100:8100"
      - "9090:9090"
      - "9100:9100"
    volumes:
      - .:/var/wow/
    restart: always
  sql:
    image: alpha-mariadb:latest
    build: etc/docker/sql
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
    ports:
      - "3306:3306"
    volumes:
      - ./etc/databases/:/etc/databases/